#PBS -q default
#PBS -N MPRA_Rep_1_2_pDNA_Pipeline_Test
#PBS -l nodes=1:ppn=8,mem=35gb
#PBS -l walltime=99:00:00
#PBS -m abe -M Jake.Gockley@yale.edu

cd $PBS_O_WORKDIR

python ~/Scripts/Pipeline.py -r EXP -s Rep_1_2_pDNA -R1 /ycga-gpfs/sequencers/illumina/sequencerZ/runs/161118_K00175_0020_AHG7FHBBXX/Data/Intensities/BaseCalls/Unaligned/Project_Jkg36/Sample_pDNA_1_2_006/pDNA-1-2-006_S6_L00*_R1_*, -R2 /ycga-gpfs/sequencers/illumina/sequencerZ/runs/161118_K00175_0020_AHG7FHBBXX/Data/Intensities/BaseCalls/Unaligned/Project_Jkg36/Sample_pDNA_1_2_006/pDNA-1-2-006_S6_L00*_R2_*, -o Rep_1_2_pDNA_Pipeline_OUT.txt

